#ifndef MY_LMML_H
#define MY_LMML_H

#include "ns3/oran-data-repository.h"
#include "ns3/oran-lm.h"
#include <ns3/vector.h>
#include "gradientDescent.hpp"
#include <map>
#include <torch/script.h>
namespace ns3
{

class MyLmMl : public OranLm
{
  protected:
    /**
     * UE related information.
     */
    struct UeInfo
    {
        uint64_t nodeId; //!< The node ID.
        uint16_t cellId; //!< The cell ID.
        uint16_t rnti;   //!< The RNTI ID.
        double loss;     //!< The loss.
        std::vector<double> rsrp;
        uint64_t Rx;     //!< Recieved packet
        uint64_t Tx;     //!< Transport packet
        uint8_t mcs;     //!< MCS
        uint16_t sizetb;
        Vector position; //!< The physical position.
    };

    /**
     * eNB related information.
     */
    struct EnbInfo
    {
        uint64_t nodeId; //!< The node ID.
        uint16_t cellId; //!< The cell ID.
        Vector position; //!< The physical position.
    };
    std::map <uint16_t, uint64_t> enbIdTrans;
  public:
    /**
     * Gets the TypeId of the MyLmMl class.
     *
     * \return The TypeId.
     */
    static TypeId GetTypeId(void);
    /**
     * Constructor of the MyLmMl class.
     */
    MyLmMl(void);
    /**
     * Destructor of the MyLmMl class.
     */
    ~MyLmMl(void) override;
    /**
     * Runs the logic specific for this Logic Module. This will retrieve the
     * location of all LTE UEs and eNBs, find the closest eNB for each UE, and if
     * this eNB is not the serving eNB, a handover Command is generated.
     *
     * \return A vector with the handover commands generated by this Logic Module.
     */
    std::vector<Ptr<OranCommand>> Run(void) override;
    
  private:
     torch::jit::script::Module m_model;
     VanillaGradientDescent vgd;
     int runTime;
     double M;
     double totalloss;
     double throughputRun;
     double throughputTotal;
     std::vector<double> times;
    /**
     * Method to get the UE information from the repository.
     *
     * \param data The data repository.
     *
     * \return A vector of UE Information structures.
     */
    std::vector<MyLmMl::UeInfo> GetUeInfos(
        Ptr<OranDataRepository> data, std::vector<MyLmMl::EnbInfo> enbinfos) const;
    /**
     * Method to get the eNB information from the repository.
     *
     * \param data The data repository.
     *
     * \return A vector of eNB Information structures.
     */
    std::vector<MyLmMl::EnbInfo> GetEnbInfos(
        Ptr<OranDataRepository> data) const;
    /**
     * Method with the logic to get the distance between UEs and eNBs
     * and generate Handover Commands if needed.
     *
     * \param data The data repository.
     * \param ueInfos A vector with the UE information.
     * \param enbInfos A vector with the eNB information.
     *
     * \return A vector with the handover commands generated.
     */
    std::vector<Ptr<OranCommand>> GetHandoverCommands(
        Ptr<OranDataRepository> data,
        std::vector<MyLmMl::UeInfo> ueInfos,
        std::vector<MyLmMl::EnbInfo> enbInfos,
        double &tq);
    double GetThroughput(std::vector<MyLmMl::UeInfo> ueInfos) const;
    double GetLoss(std::vector<MyLmMl::UeInfo> ueInfos) const;
};

} // namespace ns3

#endif
